version: '2'
services:
    easysalecivil-app:
        image: easysalecivil
        external_links:
            - easysalecivil-postgresql:postgresql
            - easysalecivil-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/EasySaleCivil
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    easysalecivil-postgresql:
        extends:
            file: postgresql.yml
            service: easysalecivil-postgresql
    easysalecivil-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: easysalecivil-elasticsearch
